// DONE REVIEWING: GITHUB COMMIT 7️⃣
export {default as Footer} from "./footer"
export {default as Hero} from "./hero"
export {default as MarketPlace} from "./market-place"
export {default as Navigation} from "./navigation"
export {default as Portfolio} from "./portfolio"
export {default as Pricing} from "./pricing"
export {default as SectionHeader} from "./section-header"
export {default as Services} from "./services"
